param([switch]$Execute)
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
$repo='C:\Users\DC\Documents\ChatGPT\Strata-Hetero';$run=Join-Path $repo 'bench\hetero\20261009-41-hetero41-direct-quality';$out=Join-Path $run 'cleanup'
$process=Get-Content (Join-Path $run 'process.json') -Raw|ConvertFrom-Json -DateKind String;$sampler=Get-Content (Join-Path $run 'sampler-process.json') -Raw|ConvertFrom-Json -DateKind String;$identity=Get-Content (Join-Path $run 'identity.json') -Raw|ConvertFrom-Json -DateKind String;$config=Get-Content (Join-Path $run 'config.json') -Raw|ConvertFrom-Json -DateKind String;$watch=Get-Content (Join-Path $run 'resource\startup-watch-result.json') -Raw|ConvertFrom-Json -DateKind String
function WriteExclusive([string]$p,$v){$b=[Text.UTF8Encoding]::new($false).GetBytes(($v|ConvertTo-Json -Depth 12)+"`n");$f=[IO.File]::Open($p,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::Read);try{$f.Write($b,0,$b.Length);$f.Flush($true)}finally{$f.Dispose()}}
function StopExact([long]$ProcessId,[string]$Exe,[string]$Created,[long]$Parent,[string]$Contains){$snapshot=@(Get-CimInstance Win32_Process);$m=@($snapshot|Where-Object{$_.ProcessId -eq $ProcessId});if($m.Count -eq 0){return @{pid=$ProcessId;status='already_absent_after_unload'}};if($m.Count -ne 1){throw "ambiguous PID $ProcessId"};$p=$m[0];if($p.ExecutablePath -ne $Exe -or $p.CreationDate.ToUniversalTime().ToString('o') -ne $Created -or ($Parent -ge 0 -and $p.ParentProcessId -ne $Parent) -or ($Contains -and -not $p.CommandLine.Contains($Contains))){throw "PID $ProcessId identity changed; refusing stop"};Stop-Process -Id ([int]$ProcessId) -ErrorAction Stop;for($i=0;$i -lt 100;$i++){Start-Sleep -Milliseconds 100;$c=Get-CimInstance Win32_Process -Filter "ProcessId = $ProcessId" -ErrorAction SilentlyContinue;if(-not $c){return @{pid=$ProcessId;exe=$Exe;create_utc=$Created;status='stopped_after_exact_revalidation'}};if($c.ExecutablePath -ne $Exe -or $c.CreationDate.ToUniversalTime().ToString('o') -ne $Created){throw "PID $ProcessId changed identity after stop"}};throw "PID $ProcessId did not exit"}
$snapshot=@(Get-CimInstance Win32_Process);function One([long]$n){$m=@($snapshot|Where-Object{$_.ProcessId -eq $n});if($m.Count -ne 1){return $null};$m[0]};$launcher=One $process.launcher_pid;$server=One $process.actual_server_child_pid;$engine=One $watch.engine_pid;$samplerLauncher=One $sampler.sampler_launcher_pid;$samplerChild=One $sampler.actual_child_pid
if(-not $launcher -or -not $server -or -not $engine -or -not $samplerLauncher -or -not $samplerChild){throw 'receipt-bound process owner missing'}
$engineCommand=$identity.engine.path+' --serve '+($config.args -join ' ')
if($launcher.ExecutablePath -ne $process.launcher_exe -or $launcher.CreationDate.ToUniversalTime().ToString('o') -ne $process.launcher_create_utc -or -not $launcher.CommandLine.Contains('serve\server.py') -or $server.ExecutablePath -ne 'C:\Python314\python.exe' -or $server.ParentProcessId -ne $launcher.ProcessId -or $server.CreationDate.ToUniversalTime().ToString('o') -ne $process.actual_server_child_create_utc -or -not $server.CommandLine.Contains($process.config) -or $engine.ExecutablePath -ne $identity.engine.path -or $engine.ParentProcessId -ne $server.ProcessId -or $engine.CreationDate.ToUniversalTime().ToString('o') -ne $watch.engine_create_utc -or $engine.CommandLine -ne $engineCommand -or $samplerLauncher.ExecutablePath -ne $sampler.sampler_launcher_exe -or $samplerLauncher.CreationDate.ToUniversalTime().ToString('o') -ne $sampler.sampler_launcher_create_utc -or $samplerChild.ExecutablePath -ne 'C:\Python314\python.exe' -or $samplerChild.ParentProcessId -ne $samplerLauncher.ProcessId -or $samplerChild.CreationDate.ToUniversalTime().ToString('o') -ne $sampler.actual_child_create_utc -or -not $samplerChild.CommandLine.Contains('hetero_resources.py')){throw 'PID/exe/parent/CreateTime/full-argv preflight failed'}
$listener=@(Get-NetTCPConnection -LocalPort 8081 -State Listen -ErrorAction SilentlyContinue);if($listener.Count -ne 1 -or $listener[0].LocalAddress -ne '127.0.0.1' -or $listener[0].OwningProcess -ne $server.ProcessId){throw '8081 not uniquely owned by run41 server'}
$status=Invoke-RestMethod -Uri 'http://127.0.0.1:8081/v1/status' -Method Get -TimeoutSec 5;if($status.model -ne $identity.model.id -or $status.engine -ne '0.1.41' -or $status.loaded -ne $true -or $status.activity.in_flight -ne 0){throw 'run41 status not expected idle model'}
$pre=[ordered]@{schema_version=1;run_id=$process.run_id;status='exact_owned_cleanup_preflight_pass';utc=[DateTime]::UtcNow.ToString('o');model=$status.model;engine=$status.engine;loaded=$status.loaded;requests=$status.activity.requests;in_flight=$status.activity.in_flight;listener_pid=$server.ProcessId;pids=@($launcher.ProcessId,$server.ProcessId,$engine.ProcessId,$samplerLauncher.ProcessId,$samplerChild.ProcessId)}
if(-not $Execute){$pre|ConvertTo-Json -Depth 8 -Compress;return}
$phase='unload'
WriteExclusive (Join-Path $out 'preflight.json') $pre
$unload=Invoke-RestMethod -Uri 'http://127.0.0.1:8081/v1/unload' -Method Post -ContentType 'application/json' -Body '{}' -TimeoutSec 120;if($unload.loaded -ne $false){throw 'POST unload did not confirm loaded=false'}
WriteExclusive (Join-Path $out 'unload.json') ([ordered]@{schema_version=1;run_id=$process.run_id;utc=[DateTime]::UtcNow.ToString('o');endpoint='POST http://127.0.0.1:8081/v1/unload';response=$unload})
$post=Invoke-RestMethod -Uri 'http://127.0.0.1:8081/v1/status' -Method Get -TimeoutSec 5;if($post.loaded -ne $false -or $post.activity.in_flight -ne 0){throw 'post-unload status not idle/unloaded'};WriteExclusive (Join-Path $out 'post-unload-status.json') $post
$stopped=@();$stopped+=StopExact $watch.engine_pid $identity.engine.path $watch.engine_create_utc $server.ProcessId ' --serve ';$stopped+=StopExact $server.ProcessId 'C:\Python314\python.exe' $process.actual_server_child_create_utc $launcher.ProcessId $process.config;$stopped+=StopExact $launcher.ProcessId $process.launcher_exe $process.launcher_create_utc -1 'serve\server.py'
$stop=Join-Path $run 'resource\STOP';if(Test-Path $stop){throw 'sampler STOP already exists'};$stopBytes=[Text.Encoding]::ASCII.GetBytes("stop`n");$f=[IO.File]::Open($stop,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::Read);try{$f.Write($stopBytes,0,$stopBytes.Length);$f.Flush($true)}finally{$f.Dispose()}
. (Join-Path $repo 'tools\hetero_jsonl_tail.ps1');$samplePath=Join-Path $run 'resource\samples.jsonl';$terminal=$false
for($i=0;$i -lt 300;$i++){Start-Sleep -Milliseconds 100;$child=Get-CimInstance Win32_Process -Filter "ProcessId = $($sampler.actual_child_pid)" -ErrorAction SilentlyContinue;try{$tail=Read-LastCompleteJsonlRecord -Path $samplePath -MaxRecordBytes 65536 -MaxTailBytes 262144 -TimestampField observed_at_utc -PartialEvidenceDirectory (Join-Path $run 'resource');if($tail.record.record_type -eq 'sampler_stopped' -and $tail.record.reason -eq 'stop_file_exists'){$terminal=$true}}catch{};if(-not $child -and $terminal){break}}
if(-not $terminal){throw 'sampler child did not terminal after STOP'};$sl=Get-CimInstance Win32_Process -Filter "ProcessId = $($sampler.sampler_launcher_pid)" -ErrorAction SilentlyContinue;if($sl -and ($sl.ExecutablePath -ne $sampler.sampler_launcher_exe -or $sl.CreationDate.ToUniversalTime().ToString('o') -ne $sampler.sampler_launcher_create_utc)){throw 'sampler launcher identity changed'};for($i=0;$i -lt 100 -and $sl;$i++){Start-Sleep -Milliseconds 100;$sl=Get-CimInstance Win32_Process -Filter "ProcessId = $($sampler.sampler_launcher_pid)" -ErrorAction SilentlyContinue};if($sl){throw 'sampler launcher did not exit'}
$summaryCode='import json,pathlib,sys;p=pathlib.Path(sys.argv[1]) / "resource" / "samples.jsonl";r=[json.loads(x) for x in p.open(encoding="utf-8")];s=[x for x in r if x.get("record_type")=="resource_sample"];t=[x for x in r if x.get("record_type")=="sampler_stopped"];assert s and len(t)==1;print(json.dumps({"status":"pass","sample_count":len(s),"terminal_count":len(t),"min_ram_gib":min(float(x["ram_gate"]["available_gib"]) for x in s),"min_commit_gib":min(float(x["commit_gate"]["available_gib"]) for x in s),"all_gates_pass":all(x["ram_gate"]["status"]=="pass" and x["commit_gate"]["status"]=="pass" and not x.get("alerts") and not x.get("errors") for x in s),"terminal":t[0]},separators=(",",":")))'
$sum=& 'C:\Python314\python.exe' -I -c $summaryCode $run;if($LASTEXITCODE -ne 0){throw 'resource summary parse failed'};$summary=($sum -join "`n")|ConvertFrom-Json -DateKind String;if($summary.status -ne 'pass' -or -not $summary.all_gates_pass){throw 'resource gate history contains fail/unknown'};WriteExclusive (Join-Path $out 'resource-summary.json') $summary
$left=@(Get-CimInstance Win32_Process|Where-Object{$_.ProcessId -in @($process.launcher_pid,$process.actual_server_child_pid,$watch.engine_pid,$sampler.sampler_launcher_pid,$sampler.actual_child_pid)});$listenFinal=@(Get-NetTCPConnection -LocalPort 8081 -State Listen -ErrorAction SilentlyContinue);if($left.Count -or $listenFinal.Count){throw 'owned process or listener remains'}
$result=[ordered]@{schema_version=1;run_id=$process.run_id;status='terminal_owned_server_and_sampler_released';utc=[DateTime]::UtcNow.ToString('o');engine_server_sampler_terminal=$true;listener8081_released=$true;sampler_was_not_killed=$true;resource_summary=$summary};WriteExclusive (Join-Path $out 'final.json') $result;$result|ConvertTo-Json -Depth 8 -Compress